CREATE TABLE "SSO_ASSISTANT_REQUEST_LOG" (
  "id" NUMBER  NOT NULL,
  "request_client" VARCHAR2(255 BYTE) ,
  "request_user" VARCHAR2(255 BYTE) ,
  "request_date" DATE ,
  "service_code" VARCHAR2(255 BYTE) ,
  "service_resp" VARCHAR2(4000 BYTE) ,
  "service_reqt" VARCHAR2(4000 BYTE) ,
  "touser_code" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SSO_ASSISTANT_REQUEST_LOG"."request_client" IS '请求发送方的程序或系统名';
COMMENT ON COLUMN "SSO_ASSISTANT_REQUEST_LOG"."request_user" IS '请求发送方的用户';
COMMENT ON COLUMN "SSO_ASSISTANT_REQUEST_LOG"."request_date" IS '请求发送时间';
COMMENT ON COLUMN "SSO_ASSISTANT_REQUEST_LOG"."service_code" IS '服务编码';
COMMENT ON COLUMN "SSO_ASSISTANT_REQUEST_LOG"."service_resp" IS '由中心端回写 - 服务数据内容(原生回执)';
COMMENT ON COLUMN "SSO_ASSISTANT_REQUEST_LOG"."service_reqt" IS '服务参数';
COMMENT ON COLUMN "SSO_ASSISTANT_REQUEST_LOG"."touser_code" IS '接收者';
COMMENT ON TABLE "SSO_ASSISTANT_REQUEST_LOG" IS '第三方请求记录表';

-- ----------------------------
-- Primary Key structure for table SSO_ASSISTANT_REQUEST_LOG
-- ----------------------------
ALTER TABLE "SSO_ASSISTANT_REQUEST_LOG" ADD CONSTRAINT "SYS_C007557" PRIMARY KEY ("id");

-- ----------------------------
-- Checks structure for table SSO_ASSISTANT_REQUEST_LOG
-- ----------------------------
ALTER TABLE "SSO_ASSISTANT_REQUEST_LOG" ADD CONSTRAINT "SYS_C007556" CHECK ("id" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

CREATE TABLE "SSO_ASSISTANT_CLIENT_VERSION" (
  "id" NUMBER  NOT NULL,
  "client_name" VARCHAR2(255 BYTE) ,
  "up_time" DATE ,
  "version" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_VERSION"."client_name" IS '程序名称';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_VERSION"."up_time" IS '发布时间';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_VERSION"."version" IS '版本号';
COMMENT ON TABLE "SSO_ASSISTANT_CLIENT_VERSION" IS '客户端版本信息表';

-- ----------------------------
-- Primary Key structure for table SSO_ASSISTANT_CLIENT_VERSION
-- ----------------------------
ALTER TABLE "SSO_ASSISTANT_CLIENT_VERSION" ADD CONSTRAINT "SYS_C007563" PRIMARY KEY ("id");

-- ----------------------------
-- Checks structure for table SSO_ASSISTANT_CLIENT_VERSION
-- ----------------------------
ALTER TABLE "SSO_ASSISTANT_CLIENT_VERSION" ADD CONSTRAINT "SYS_C007562" CHECK ("id" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;


CREATE TABLE "SSO_ASSISTANT_CLIENT_LOG" (
  "id" NUMBER  NOT NULL,
  "user_code" VARCHAR2(255 BYTE) ,
  "user_ip" VARCHAR2(255 BYTE) ,
  "user_mac" VARCHAR2(255 BYTE) ,
  "client_version" VARCHAR2(255 BYTE) ,
  "online_state" VARCHAR2(3 BYTE) ,
  "endtime" DATE ,
  "createtime" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_LOG"."user_code" IS '登录用户编码';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_LOG"."user_ip" IS '登录用户ip';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_LOG"."user_mac" IS '登录用户mac';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_LOG"."cilent_version" IS '登录的客户端版本号';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_LOG"."online_state" IS '在线状态 0: 离线 1:在线 2:离开 9:忙碌';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_LOG"."endtime" IS '离线时间';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_LOG"."createtime" IS '在线时间';
COMMENT ON TABLE "SSO_ASSISTANT_CLIENT_LOG" IS '客户端登录日志';

-- ----------------------------
-- Primary Key structure for table SSO_ASSISTANT_CLIENT_LOG
-- ----------------------------
ALTER TABLE "SSO_ASSISTANT_CLIENT_LOG" ADD CONSTRAINT "SYS_C007565" PRIMARY KEY ("id");

-- ----------------------------
-- Checks structure for table SSO_ASSISTANT_CLIENT_LOG
-- ----------------------------
ALTER TABLE "SSO_ASSISTANT_CLIENT_LOG" ADD CONSTRAINT "SYS_C007564" CHECK ("id" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;


CREATE TABLE "SSO_ASSISTANT_TOMESSAGE_LOG" (
  "id" NUMBER  NOT NULL,
  "touser_code" VARCHAR2(255 BYTE) ,
  "toservice_title" VARCHAR2(255 BYTE) ,
  "toservice_resp" VARCHAR2(4000 BYTE) ,
  "TIPS_TYPE" VARCHAR2(255 BYTE) ,
  "state" NUMBER  DEFAULT 0,
  "request_time" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SSO_ASSISTANT_TOMESSAGE_LOG"."touser_code" IS '接受者编码';
COMMENT ON COLUMN "SSO_ASSISTANT_TOMESSAGE_LOG"."toservice_title" IS '接收的信息标题 (改造后的回执)';
COMMENT ON COLUMN "SSO_ASSISTANT_TOMESSAGE_LOG"."toservice_resp" IS '接收的信息内容 (改造后的回执)';
COMMENT ON COLUMN "SSO_ASSISTANT_TOMESSAGE_LOG"."TIPS_TYPE" IS '消息类型 - 根据类型执行客户端不同操作';
COMMENT ON COLUMN "SSO_ASSISTANT_TOMESSAGE_LOG"."state" IS '查看状态 - 0:未查看 1:已查看 初始0';
COMMENT ON COLUMN "SSO_ASSISTANT_TOMESSAGE_LOG"."request_time" IS '读取消息时间';
COMMENT ON TABLE "SSO_ASSISTANT_TOMESSAGE_LOG" IS '客户端消息表';

-- ----------------------------
-- Primary Key structure for table SSO_ASSISTANT_TOMESSAGE_LOG
-- ----------------------------
ALTER TABLE "SSO_ASSISTANT_TOMESSAGE_LOG" ADD CONSTRAINT "SYS_C007561" PRIMARY KEY ("id");

-- ----------------------------
-- Checks structure for table SSO_ASSISTANT_TOMESSAGE_LOG
-- ----------------------------
ALTER TABLE "SSO_ASSISTANT_TOMESSAGE_LOG" ADD CONSTRAINT "SYS_C007560" CHECK ("id" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;


CREATE TABLE "SSO_ASSISTANT_CLIENT_REGISTER" (
  "id" VARCHAR2(100 BYTE)  NOT NULL,
  "SERVER_CODE" VARCHAR2(200 BYTE) ,
  "SERVER_NAME" VARCHAR2(200 BYTE) ,
  "CODE" VARCHAR2(200 BYTE) ,
  "TIPS_TYPE" VARCHAR2(100 BYTE) ,
  "SERVER_URL" VARCHAR2(500 BYTE) ,
  "SERVER_URL_BAK" VARCHAR2(500 BYTE) ,
  "SERVER_DISCREPTION" VARCHAR2(2000 BYTE) ,
  "FG_ACTIVE" NUMBER(10,0) ,
  "INSERT_TIME" DATE ,
  "UPDATE_TIME" DATE ,
  "DELETE_TIME" DATE ,
  "INSERT_USER" VARCHAR2(20 BYTE) ,
  "UPDATE_USER" VARCHAR2(20 BYTE) ,
  "DELETE_USER" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."id" IS 'id主键';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."SERVER_CODE" IS '服务编码';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."SERVER_NAME" IS '服务名称';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."CODE" IS '返参关键字code';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."TIPS_TYPE" IS '消息类型({key:''1'',text:''服务转发''},{key:''2'',text:''消息提醒''},{key:''3'',text:''截留提醒''})';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."SERVER_URL" IS '服务rul';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."SERVER_URL_BAK" IS '备用URl';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."SERVER_DISCREPTION" IS '描述';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."FG_ACTIVE" IS '状态(0:删除 ，1：正常)';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."INSERT_TIME" IS '创建时间';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."DELETE_TIME" IS '删除时间';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."INSERT_USER" IS '创建人';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."UPDATE_USER" IS '更新人';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_REGISTER"."DELETE_USER" IS '删除人';
COMMENT ON TABLE "SSO_ASSISTANT_CLIENT_REGISTER" IS '客户端注册 / 服务注册';

-- ----------------------------
-- Checks structure for table SSO_ASSISTANT_CLIENT_REGISTER
-- ----------------------------
ALTER TABLE "SSO_ASSISTANT_CLIENT_REGISTER" ADD CONSTRAINT "SYS_C007558" CHECK ("id" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;


CREATE TABLE "SSO_ASSISTANT_CLIENT_USER" (
  "id" VARCHAR2(100 BYTE)  NOT NULL,
  "SERVER_CODE" VARCHAR2(200 BYTE) ,
  "USER_CODE" VARCHAR2(200 BYTE) ,
  "USER_NAME" VARCHAR2(200 BYTE) ,
  "JGBM" VARCHAR2(100 BYTE) ,
  "JGMC" VARCHAR2(100 BYTE) ,
  "FG_ACTIVE" NUMBER(10,0) ,
  "INSERT_TIME" DATE ,
  "UPDATE_TIME" DATE ,
  "DELETE_TIME" DATE ,
  "INSERT_USER" VARCHAR2(20 BYTE) ,
  "UPDATE_USER" VARCHAR2(20 BYTE) ,
  "DELETE_USER" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."id" IS 'id主键';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."SERVER_CODE" IS '服务编码';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."USER_CODE" IS '用户编码';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."USER_NAME" IS '用户名称';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."JGBM" IS '机构编码';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."JGMC" IS '机构名称';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."FG_ACTIVE" IS '状态（0：删除   1：正常）';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."INSERT_TIME" IS '创建时间';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."DELETE_TIME" IS '删除时间';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."INSERT_USER" IS '创建人';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."UPDATE_USER" IS '更新人';
COMMENT ON COLUMN "SSO_ASSISTANT_CLIENT_USER"."DELETE_USER" IS '删除人';
COMMENT ON TABLE "SSO_ASSISTANT_CLIENT_USER" IS '用户订阅信息表';

-- ----------------------------
-- Checks structure for table SSO_ASSISTANT_CLIENT_USER
-- ----------------------------
ALTER TABLE "SSO_ASSISTANT_CLIENT_USER" ADD CONSTRAINT "SYS_C007559" CHECK ("id" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;




